/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./*.html", "./assets/**/*.js"],
  theme: {
    extend: {
      "colors": {
          "tertiary": "#3c1b00",
          "inverse-surface": "#303030",
          "on-error-container": "#93000a",
          "surface-container-high": "#eae7e7",
          "on-secondary": "#ffffff",
          "background": "#fcf9f8",
          "on-primary-fixed": "#001c38",
          "surface-muted": "#F4F8FB",
          "secondary": "#00658d",
          "inverse-on-surface": "#f3f0ef",
          "tertiary-fixed-dim": "#ffb780",
          "on-primary-fixed-variant": "#204874",
          "primary-container": "#0d3b66",
          "on-secondary-fixed": "#001e2d",
          "surface-container-low": "#f6f3f2",
          "outline-variant": "#c3c6d0",
          "on-secondary-fixed-variant": "#004c6b",
          "on-secondary-container": "#005576",
          "success-green": "#2D6A4F",
          "surface-variant": "#e5e2e1",
          "surface-container": "#f0eded",
          "primary": "#002546",
          "on-surface-variant": "#42474f",
          "surface-bright": "#fcf9f8",
          "tertiary-fixed": "#ffdcc4",
          "surface-container-lowest": "#ffffff",
          "secondary-fixed-dim": "#82cfff",
          "on-tertiary-fixed": "#2f1400",
          "outline": "#737780",
          "primary-fixed": "#d3e4ff",
          "surface": "#fcf9f8",
          "glass-border": "rgba(255, 255, 255, 0.3)",
          "on-primary": "#ffffff",
          "surface-tint": "#3a608d",
          "secondary-container": "#73cafe",
          "on-tertiary-container": "#9c4a11",
          "on-primary-container": "#81a6d7",
          "on-background": "#1b1c1c",
          "on-error": "#ffffff",
          "on-tertiary-fixed-variant": "#6f3800",
          "tertiary-container": "#5c2d00",
          "on-tertiary": "#ffffff",
          "on-surface": "#1b1c1c",
          "surface-dim": "#dcd9d9",
          "error-container": "#ffdad6",
          "surface-container-highest": "#e5e2e1",
          "secondary-fixed": "#c6e7ff",
          "glass-surface": "rgba(255, 255, 255, 0.7)",
          "error": "#ba1a1a",
          "primary-fixed-dim": "#a4c9fc",
          "inverse-primary": "#a4c9fc"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "section-gap": "100px",
          "gutter-mobile": "16px",
          "margin-desktop": "80px",
          "margin-mobile": "20px",
          "gutter-desktop": "24px",
          "unit": "4px"
      },
      "fontFamily": {
          "body-md": ["Hanken Grotesk"],
          "headline-lg": ["Noto Serif"],
          "title-lg": ["Hanken Grotesk"],
          "body-lg": ["Hanken Grotesk"],
          "display-lg": ["Noto Serif"],
          "headline-md": ["Noto Serif"],
          "headline-lg-mobile": ["Noto Serif"],
          "label-md": ["Hanken Grotesk"]
      },
      "fontSize": {
          "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
          "headline-lg": ["40px", { "lineHeight": "1.2", "fontWeight": "600" }],
          "title-lg": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
          "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
          "display-lg": ["56px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
          "headline-md": ["28px", { "lineHeight": "1.3", "fontWeight": "600" }],
          "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
          "label-md": ["14px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
